server:
  port: 8012

spring:
  application:
    name: config_server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          force-pull: true
          password: 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
#         searchPaths: usersws,zuul
          uri: https://github.com/vishal210893/ConfigRepo
          username: vishal210893
          default-label: main
  rabbitmq:
    addresses: amqps://mnufxmxx:BRav08eNOG_NEZI8fSgySKK-0EiNTm8_@lionfish.rmq.cloudamqp.com/mnufxmxx
#        native:
#          searchLocations: file://${user.home}/Desktop/dev/config-server-nfs
#  profiles:
#    active: native

# ACTUATOR PROPERTIES
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    build:
      enabled: true
    java:
      enabled: true
