server:
  port: 8012

spring:
  application:
    name: config_server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          force-pull: true
          password: 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
#         searchPaths: usersws,zuul
          uri: https://github.com/vishal210893/ConfigRepo
          username: vishal210893
          default-label: main
#        native:
#          searchLocations: file://${user.home}/Desktop/dev/config-server-nfs
#  profiles:
#    active: native
#  rabbitmq:
#    host: localhost
#    password: guest
#    port: 5672
#    username: guest

# ACTUATOR PROPERTIES
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    build:
      enabled: true
    java:
      enabled: true
