server:
  port: ${PORT:0}

spring:
  application:
    name: photoapp-api-user
  h2:
    console:
      enabled: true
  rabbitmq:
    addresses: amqps://mnufxmxx:BRav08eNOG_NEZI8fSgySKK-0EiNTm8_@lionfish.rmq.cloudamqp.com/mnufxmxx

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    #appname: photoapp-api-user

# ACTUATOR PROPERTIES
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    build:
      enabled: true
    java:
      enabled: true

login:
  url:
    path: /users/login
token:
  secret: hfgry463hf746hf573ydh475fhy5739
  expiration_time: '864000000'
gateway:
  ip: 10.14.60.178