spring:
  application:
    name: PhotoApp account management

server:
  port: '0'

# ACTUATOR PROPERTIES
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    build:
      enabled: true
    java:
      enabled: true

#EUREKA PROPERTIES
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
#    statusPageUrlPath: /account/status/check  # By Default it will call /actuator/info